name: Build & Review
on: [pull_request]

jobs:
  build-review:
    uses: machinology/mach-shared-workflows/.github/workflows/build-review-automerge.yml@v1
    secrets: inherit
    permissions:
      pull-requests: write
      contents: write
