name: Release
on:
  workflow_dispatch: # manual only

jobs:
  release:
    uses: machinology/mach-shared-workflows/.github/workflows/release.yml@v1
    secrets: inherit
    permissions:
      contents: write
