name: Update flakes

on:
  workflow_dispatch:
    inputs:
      flakes-to-update:
        description: "Specific flake inputs to be updated (space-separated. Leave empty to update all flakes."
        required: false
        type: string
  schedule:
    - cron: "0 12 * * 0" # every Sunday at 12pm

jobs:
  update-flakes:
    uses: machinology/mach-shared-workflows/.github/workflows/update-flakes.yml@v1
    permissions:
      pull-requests: write
      contents: write
